# TomyJan Clash Base Configuration With AdGuardHome

# 混合端口 HTTP 和 SOCKS5 用一个端口
mixed-port: 7890
# HTTP 代理端口
# port: 7890
# SOCKS5 代理端口
# socks-port: 7891
# 本地 SOCKS5 / HTTP(S) 服务认证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Linux 和 macOS 的 redir 代理端口
# redir-port: 7892

# 允许局域网的连接, 可用来共享代理
allow-lan: false

# 仅在将allow-lan设置为 true 时适用
# "*": 绑定所有IP地址
# "10.0.2.8": 绑定单个 IPv4 地址
# "[2400:3200::]": 绑定单个IPv6地址
bind-address: "*"
ipv6: true


# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule
# silent / error / warning / info / debug
log-level: info
# Clash 的 RESTful API
external-controller: 127.0.0.1:9090


# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# http://127.0.0.1:9090/ui/#/
# external-ui: folder
# yacd面板：  https://github.com/haishanh/yacd
# Razord面板：http://clash.razord.top/#/proxies
# external-ui: dashboard

# RESTful API 的口令 (可选)
# secret: ""


# 实验性功能
experimental:
  ignore-resolve-fail: false # 忽略 DNS 解析失败，默认值为 true
  # interface-name: en0 # outbound interface name

# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效
# hosts:
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'


# Clash for Windows
cfw-latency-timeout: 3000
cfw-latency-url: http://cp.cloudflare.com/generate_204
cfw-conn-break-strategy: true

# Clash for Android
clash-for-android: 
  ui-subtitle-pattern: "\\[\w\\][\u4e00-\u9fa5]+[A-Z]"

# Stash
url-rewrite:
    - ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
    - ^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 302


# 1. clash DNS 请求逻辑：
#   (1) 当访问一个域名时， nameserver 与 fallback 列表内的所有服务器并发请求，得到域名对应的 IP 地址。
#   (2) clash 将选取 nameserver 列表内，解析最快的结果。
#   (3) 若解析结果中，IP 地址属于 国外，那么 clash 将选择 fallback 列表内，解析最快的结果。
#
# 2. clash DNS 配置注意事项：
#   (1) 如果您为了确保 DNS 解析结果无污染，请仅保留列表内以 tls:// 或 https:// 开头的 DNS 服务器，但是通常对于国内域名没有必要。
#   (2) 如果您不在乎可能解析到污染的结果，更加追求速度。请将 nameserver 列表的服务器插入至 fallback 列表内，并移除重复项。
#
# 3. 关于 DNS over HTTPS (DoH) 和 DNS over TLS (DoT) 的选择：
#   对于两项技术双方各执一词，而且会无休止的争论，各有利弊。各位请根据具体需求自行选择，但是配置文件内默认启用 DoT，因为目前国内没有封锁或管制。
#   DoH: 以 https:// 开头的 DNS 服务器。拥有更好的伪装性，且几乎不可能被运营商或网络管理封锁，但查询效率和安全性可能略低。
#   DoT: 以 tls:// 开头的 DNS 服务器。拥有更高的安全性和查询效率，但端口有可能被管制或封锁。
#   若要了解更多关于 DoH/DoT 相关技术，请自行查阅规范文档。

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
     - 223.5.5.5
     - 8.8.4.4
  enhanced-mode: redir-host # 模式：redir-host 或 fake-ip
  # fake-ip-range: 198.18.0.1/16 #
  # fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
  #    - '*.lan'
  #    - localhost.ptlogin2.qq.com
  nameserver:
     - tls://dns.amoe.cc:853
     - https://dns.amoe.cc/dns-query
  fallback:
     - tls://1.0.0.1:853
     - tls://dns.google:853
     - https://cloudflare-dns.com/dns-query
     - https://dns.google/dns-query
  fallback-filter:
     geoip: true
     ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
       - 240.0.0.0/4
       - 0.0.0.0/32
       - 127.0.0.1/32
     domain:
       - localhost.ptlogin2.qq.com
       - localhost.sec.qq.com
       - +.facebook.com
       - +.twitter.com
       - +.google.com
       - +.googleapis.com
       - +.google.cn
       - +.googleapis.cn
       - +.xn--ngstr-lra8j.com
       - +.googlevideo.com
       - +.gvt1.com
       - +.gmail.com
       - +.youtube.com
       - +.youtu.be
       - +.gvt0.com
       - +.gvt2.com
       - +.gvt3.com
       - +.gstatic.com
       - +.265.com
       - +.2mdn.net
       - +.app-measurement.com
       - +.c.admob.com
       - +.clickserve.dartsearch.net
       - +.crl.pki.goog
       - +.doubleclick.net
       - +.firebase-settings.crashlytics.com
       - +.google-analytics.com
       - +.googleadservices.com
       - +.googleanalytics.com
       - +.googleoptimize.com
       - +.googlesyndication.com
       - +.googletagmanager.com
       - +.googletagservices.com


